### ISSUE TITLE
python2下面报错如何解决？

### ISSUE THREAD

**Issue by zye3511237** [codeif/PyTEA#1]
您好，这个库在python2.X下面运行好像有点问题，我在python2.7下面用这个库如果加密的内容有中文的话会报这个错（我将库里面的__init__.py和compat.py单独提出来了，__init__文件改成了pytea.py,直接install这个库的话也是报同样的错）
![image](https://user-images.githubusercontent.com/21077599/31607894-ce19d29a-b2a0-11e7-9edc-4d98e0ffde1a.png)
没有中文的话会报另一个错
![image](https://user-images.githubusercontent.com/21077599/31608013-43ad9bf4-b2a1-11e7-9432-12b64e423b5f.png)
请问下是我哪里用的有问题还是库本身在2.X下面运行有问题呢，倒是看到compat.py里面做了兼容，这个要怎么改呢，能否出一个专门针对python2.X版本的？

**Comment by codeif** [comment]
已修复，多谢🙏
